sudo: required
services:
- docker
language: bash
script:
- export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master"
  ]]; then echo "latest"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
- export REPO=zepp/netool
- docker build -t $REPO:$TAG .
after_success:
- docker login -u="$HUB_USER" -p="$HUB_PASS"
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
  docker tag $REPO:$TAG $REPO:$TRAVIS_BUILD_NUMBER; docker push $REPO:$TRAVIS_BUILD_NUMBER;
  fi
- docker push $REPO:$TAG
notifications:
  slack:
    secure: gpYh8mRopKwqGDxaTfSfkJIKxA4GZWNiCE8U5GQfRknCMahiWVWm5+/V6J/0UMerplulUqf0z4kpqvgj74/eY/+XPuo2nLUQk5u8suxM+y8Uov+pQBQRfgyWVOhEY6pmh+fO4EqBU9rNlbe6UhQcR4v7j6sU+Uq60veS0KiTInJEHI0D9qnMI1WccJzBRAtW/UvWe72/dNdAjfSZ0j0elBq+Ntt0gldLZZnaaXJQb4LQhq0Qs5Jui++S9hkDjIPG84kANL+GVFHX07fTzlRRUcls4GCNu0Zncf9cm6UVEGs8KYQ2ny0FXen7cKBzFiKGO24Bj7UR6xmG6tegagYgaPZGIJQ82ujpeaj876NZ8QckHm+XOnpQdXOhopCvEYZOvBSVP24a1UgcWS4PFbfVgpSezSpcBNGAkzxcgj7k71aPsBb0AWM7VSi7fPReIO4Ny1tFMsuPWf2TJea741REOxRSpH4MWsbHvVYB3L5oLL9NoXaAHqW2GeYPdRkxhiae7R0wervUzWceOAF/dEzD7FHF4lPXuY7KHSrL5hBCRYEBs383LvMTCBLrNcRJkeasTvqJgyKqbRO+ie1HqAKEKBuorHrSouET7h1j90EyGSjfQNppwiECrvTUZkHfcvuYjqmycvvYWVYV/P+BdR91Ob+ajP7cVd0qlGYncWytwXY=
